runtime: python27
api_version: 1
threadsafe: true

skip_files:
  - gwt-unitCache/

handlers:
  - url: /
    static_files: war/ya_kraina.html
    upload: war/ya_kraina.html


  - url: /(.*)
    static_files: war/\1
    upload: war/(.*)
